import '../../core/constants/app_constants.dart';

/// Mock summary service for UI development.
/// Will be replaced with real AI backend service later.
class MockSummaryService {
  /// Simulates uploading a PDF file.
  Future<String> uploadPdf(String fileName) async {
    await Future.delayed(AppConstants.mockApiDelay);
    return 'upload_${DateTime.now().millisecondsSinceEpoch}';
  }

  /// Simulates AI summarization of a PDF document.
  Future<String> summarize(String uploadId) async {
    await Future.delayed(const Duration(seconds: 3));
    return _mockSummaryMarkdown;
  }

  /// Returns a list of mock summary history items.
  Future<List<MockSummaryItem>> getHistory() async {
    await Future.delayed(const Duration(seconds: 1));
    return List.generate(
      AppConstants.mockHistoryItemCount,
      (i) => MockSummaryItem(
        id: 'sum_$i',
        fileName: 'Document_${i + 1}.pdf',
        title: 'Summary of Document ${i + 1}',
        snippet: 'This document discusses key findings in the field of...',
        createdAt: DateTime.now().subtract(Duration(hours: i * 3)),
        fileSize: '${(i + 1) * 256} KB',
      ),
    );
  }
}

/// Model for a summary history item.
class MockSummaryItem {
  final String id;
  final String fileName;
  final String title;
  final String snippet;
  final DateTime createdAt;
  final String fileSize;

  const MockSummaryItem({
    required this.id,
    required this.fileName,
    required this.title,
    required this.snippet,
    required this.createdAt,
    required this.fileSize,
  });
}

/// Long-form mock markdown summary content.
const String _mockSummaryMarkdown = '''
# Document Summary

## Key Findings

This document presents a comprehensive analysis of **artificial intelligence** applications in modern document processing workflows.

### 1. Introduction
The rapid advancement of AI technologies has transformed how organizations handle document management and information extraction.

### 2. Main Points

- **Natural Language Processing (NLP)** enables automatic text summarization
- **Machine Learning** models can classify documents with 95%+ accuracy
- **Deep Learning** approaches outperform traditional methods in:
  - Text extraction
  - Sentiment analysis
  - Topic modeling

### 3. Methodology

The study employed a mixed-methods approach:

1. Quantitative analysis of 1,000+ documents
2. Qualitative interviews with 50 industry professionals
3. Comparative benchmarking of 5 AI models

### 4. Results

| Metric | Traditional | AI-Powered |
|--------|-----------|------------|
| Accuracy | 72% | 94% |
| Speed | 5 min/doc | 0.3 sec/doc |
| Cost | \$2.50/doc | \$0.05/doc |

### 5. Conclusion

> AI-powered document processing represents a paradigm shift in how organizations manage information assets.

The findings suggest that organizations adopting AI summarization tools can achieve **10x improvement** in processing speed while maintaining high accuracy.

---
*Generated by AI PDF Summarizer*
''';
